### ISSUE TITLE
Windows: enumerating variable names

### ISSUE THREAD

**Issue by MOZGIII** [iTrooz/efiboot-rs#10]
I'm aware that on Windows there's no API for enumerating EFI var names, so I created this: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/37431478-expose-uefi-s-getnextvariablename-to-the-userspace

I'd like everyone interested to vote this up! Thanks in advance.

**Comment by iTrooz** [comment]
Not sure how it was in 2019, but now we can enumerate variable names
Example: https://github.com/iTrooz/firmware-variables/blob/9a54da5aca38eaf345c24a3ac1935063f94ab9d8/src/firmware_variables/platform/win32.py#L73 (credit: netaneld122)

(Btw your link is expired)

**Comment by MOZGIII** [comment]
Very interesting, I wasn't aware of this. This is definitely from elsewhere in the API that we use here currently, as that one is from the ntdll (which can be found at https://docs.rs/ntapi/latest/ntapi/ntexapi/fn.NtEnumerateSystemEnvironmentValuesEx.html), and we use `SetFirmwareEnvironmentVariableExW`and the like from `winbase.h` (available via `winapi` and `windows` crates).
