### ISSUE TITLE
Modify VarReader::read() to read dynamically sized variable

### ISSUE THREAD

**Issue by iTrooz** [iTrooz/efiboot-rs#46]
It is possible to read dynamically sized variables, so I'd like it to be exposed directly in VarReader (because its easier to work with, and APIs are all about making things easier, right ?)

Example on Windows: https://github.com/netaneld122/firmware-variables/blob/a3f7d5993f043816fc4f9a5cdf4aa2553d2c7fc4/src/firmware_variables/variables.py#L44

I think that would also deprecate VarReaderEx

**Comment by iTrooz** [comment]
I don't have perms to do so but let's say I'm assigned to this issue

**Comment by vtavernier** [comment]
> It is possible to read dynamically sized variables, so I'd like it to be exposed directly in VarReader (because its easier to work with, and APIs are all about making things easier, right ?)
> 
> Example on Windows: https://github.com/netaneld122/firmware-variables/blob/a3f7d5993f043816fc4f9a5cdf4aa2553d2c7fc4/src/firmware_variables/variables.py#L44
> 
> I think that would also deprecate VarReaderEx

That seems like a good idea, the current API isn't the best to be honest (I was just starting Rust back then) so it makes sense to change it.
