### ISSUE TITLE
Update CODEOWNERS file

### ISSUE THREAD

**Issue by vtavernier** [iTrooz/efiboot-rs#60]
Hello,

Since you're now maintaining the project, you might want to change the CODEOWNERS file so you get review requests sent to you instead: https://github.com/iTrooz/efiboot-rs/blob/0caadaeb56d8fed5a452cebf97c51cdc18de4300/CODEOWNERS#L1

Best regards

**Comment by iTrooz** [comment]
Oops, I'm going to do that ASAP, thanks
